# Copyright Nixort <https://github.com/Nixort> 2026.
#
# License: GNU General Public License v3.0 only.
# You can find the license file in the project root.
#
# Causal Frontier Ratchet (CFR).

[package]
name        = "cfr-core"
description = "CFR continuous group key management: causal graph, membership, node keys"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
repository.workspace   = true
authors.workspace      = true

[dependencies]
cfr-crypto = { workspace = true }
thiserror     = { workspace = true }

[features]
default = ["std"]
std     = ["thiserror/std", "cfr-crypto/std"]
pq      = ["cfr-crypto/pq"]
persistence = ["cfr-crypto/persistence"]

[lints]
workspace = true
